### PR TITLE
Neutrino

### PR DESCRIPTION
**Pull request by NickSwainston**
Set up the simple Neutrino trigger logic. I haven't updated the flow diagram yet because that will make merge conflicts so I'll do it after PR #37

### CODE REVIEW

**Comment by NickSwainston** [comment]
Tests and flow charts are all updated so the pull request is ready for a review

**Comment by PaulHancock** [comment]
When selecting Neutrino events:
- hide swift rate signf, and fermi prob
- hide antares min ranking when selecting AMON as event telescope
- antares and AMON trigger an error `Event telescope: Select a valid choice. That choice is not one of the available choices.`

**Review by PaulHancock — CHANGES_REQUESTED** [review]
See comments above

**Comment by NickSwainston** [comment]
Fixed the above bugs

**Review by PaulHancock — APPROVED** [review]

**Pull request merged**
