### PR TITLE
Backend rename

### PR DESCRIPTION
**Pull request by NickSwainston**
- Renamed all the back end, so it matches the front end, finishes #57 
- Made sure variables and decision reason logs are consistent with the renames

### CODE REVIEW

**Comment by NickSwainston** [comment]
Gunna merge this one in to prevent issues with future merges so hopefully, it all looks alright!

**Comment by PaulHancock** [comment]
Yup, everything looks good. You did a much more thorough renaming that I was expecting. Hopefully future developers will thank you for this.

**Review by PaulHancock — COMMENTED** [review]
Approve

**Comment by NickSwainston** [comment]
I think this will help future me as the renaming makes some of the logic clearer

**Pull request merged**
